### ISSUE TITLE
Implement new s-boxes

### ISSUE THREAD

**Issue by moCello** [dusk-network/zelbet#13]
**Describe what you want implemented** 
The primes on the s-boxes have changed since we declare a value <660 for the BLS prime.

This has lead to differences in the sbox.

**Describe "Why" this is needed**
To be concise with the paper.

**Describe alternatives you've considered**
NA

**Additional context**
Original [issue](https://github.com/dusk-network/reinforced-concrete/issues/9) in `reinforced-concrete`

**Comment by xevisalle** [comment]
This was already solved in https://github.com/dusk-network/reinforced-concrete/commit/6afd62a67f0907a5f5b0d13bc6845345e9654e08 .
